Repository libui-ng/libui-ng, pull requests merged in 2022-01, with the labels that each got.

#21 [Old PR libui#316] Resizeable Window
  CHANGELOG.md
  darwin/window.m
  test/menus.c
  ui.h
  unix/window.c
  windows/window.cpp
Labels: old repo

#22 [Old PR libui#468] Add missing ComboBox features
  CHANGELOG.md
  darwin/combobox.m
  test/page4.c
  ui.h
  unix/combobox.c
  windows/combobox.cpp
Labels: old repo

#25 [Old PR libui#222] Detecting the number of children where deletion is supported
  darwin/box.m
  darwin/form.m
  ui.h
  unix/box.c
  unix/form.c
  windows/box.cpp
  windows/form.cpp
Labels: old repo

#18 [Old PR libui#508] Add advanced uiTable test suite to page17.
  test/main.c
  test/meson.build
  test/page17.c
  test/test.h
Labels: old repo

#16 [Old PR libui#505] Implement proper uiTableModel stamps for unix.
  unix/table.h
  unix/tablemodel.c
Labels: old repo

#17 [Old PR libui##507] Fix table editing redraw code on all platforms.
  common/tablemodel.c
  darwin/tablecolumn.m
  windows/tableediting.cpp
Labels: old repo

#19 [Old PR libui#509] darwin: Fix uiTable checkbox value not calling SetCellValue().
  darwin/tablecolumn.m
Labels: old repo

#20 [Old PR libui#515] Fix table row inserted/deleted documentation and windows implementation.
  ui.h
  windows/table.cpp
Labels: old repo

#23 [Old PR libui#512] Add new API functions to get and set the visibility of table headers.
  darwin/table.m
  test/page16.c
  ui.h
  unix/table.c
  windows/table.cpp
Labels: old repo

#24 [Old PR libui#513] Add new API functions for table header clicks and sort indicators.
  darwin/table.h
  darwin/table.m
  darwin/tablecolumn.m
  test/page16.c
  ui.h
  unix/table.c
  windows/table.cpp
  windows/table.hpp
Labels: old repo

#40 [Old PR libui#190] add uiOpenFolder API
  CHANGELOG.md
  darwin/stddialogs.m
  examples/controlgallery/main.c
  test/page5.c
  ui.h
  unix/stddialogs.c
  windows/stddialogs.cpp
Labels: old repo

#46 uiComboboxNumItems()
  CHANGELOG.md
  darwin/combobox.m
  test/page4.c
  ui.h
  unix/combobox.c
  windows/combobox.cpp
Labels: enhancement

#39 Add AUTHORS.md
  AUTHORS.md
  doc/build_authors_file.py
Labels: documentation
